workflows:
  ios-local-build:
    name: iOS Local Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      ios_signing:
        distribution_type: development # Thay đổi thành development để sử dụng local
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
        - $FLUTTER_ROOT/.pub-cache
        - $FCI_BUILD_DIR/build
    scripts:
      - name: Install dependencies
        script: | 
          flutter pub get
      - name: Install pods
        script: | 
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: | 
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r app.ipa Payload
    artifacts:
      - build/ios/iphoneos/app.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your.email@example.com # Thay đổi email của bạn
        notify:
          success: true
          failure: true 