// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjNqSkF0gSHenLMLQt43mUp9RWVNDcOrc',
    appId: '1:786672391220:web:dc1d47b2b81ddcdc5f6661',
    messagingSenderId: '786672391220',
    projectId: 'listening-spaced-repetition',
    authDomain: 'listening-spaced-repetition.firebaseapp.com',
    storageBucket: 'listening-spaced-repetition.appspot.com',
    measurementId: 'G-ZG39KN5SED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4SLi6uIEB4D_5Uhl5TZ2fqKHEbO3ci7g',
    appId: '1:786672391220:android:20635eb5680d942e5f6661',
    messagingSenderId: '786672391220',
    projectId: 'listening-spaced-repetition',
    storageBucket: 'listening-spaced-repetition.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlVSOEEgODUKQcQUItjifVrYdcBffFNz8',
    appId: '1:786672391220:ios:942192e9ad378e355f6661',
    messagingSenderId: '786672391220',
    projectId: 'listening-spaced-repetition',
    storageBucket: 'listening-spaced-repetition.appspot.com',
    androidClientId: '786672391220-63ak3u450c236jfd5vfa450ueskcau6g.apps.googleusercontent.com',
    iosClientId: '786672391220-bdcrtbs6r2qrklk8u0v31q47afubqtt5.apps.googleusercontent.com',
    iosBundleId: 'com.example.listeningSpacedRepetition',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlVSOEEgODUKQcQUItjifVrYdcBffFNz8',
    appId: '1:786672391220:ios:942192e9ad378e355f6661',
    messagingSenderId: '786672391220',
    projectId: 'listening-spaced-repetition',
    storageBucket: 'listening-spaced-repetition.appspot.com',
    androidClientId: '786672391220-63ak3u450c236jfd5vfa450ueskcau6g.apps.googleusercontent.com',
    iosClientId: '786672391220-bdcrtbs6r2qrklk8u0v31q47afubqtt5.apps.googleusercontent.com',
    iosBundleId: 'com.example.listeningSpacedRepetition',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjNqSkF0gSHenLMLQt43mUp9RWVNDcOrc',
    appId: '1:786672391220:web:24a06a14594a0c635f6661',
    messagingSenderId: '786672391220',
    projectId: 'listening-spaced-repetition',
    authDomain: 'listening-spaced-repetition.firebaseapp.com',
    storageBucket: 'listening-spaced-repetition.appspot.com',
    measurementId: 'G-G723CTYECH',
  );
}
