platform :ios, '13.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Khai báo các Pods của Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  # Khai báo GoogleSignIn
  pod 'GoogleSignIn'

  # Khai báo device_info_plus với đường dẫn local
  pod 'device_info_plus', :path => '.symlinks/plugins/device_info_plus/ios'

  # Khai báo các plugin Flutter khác với đường dẫn local
  pod 'flutter_inappwebview', :path => '.symlinks/plugins/flutter_inappwebview/ios'
  pod 'pointer_interceptor', :path => '.symlinks/plugins/pointer_interceptor/ios'
  pod 'google_sign_in_ios', :path => '.symlinks/plugins/google_sign_in_ios/darwin'
  pod 'irondash_engine_context', :path => '.symlinks/plugins/irondash_engine_context/ios'
  pod 'super_native_extensions', :path => '.symlinks/plugins/super_native_extensions/ios'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end